/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VocabularyIndexRouteImport } from './routes/vocabulary/index'
import { Route as VocabularyNewRouteImport } from './routes/vocabulary/new'
import { Route as VocabularyIdRouteImport } from './routes/vocabulary/$id'
import { Route as VocabularyEditIdRouteImport } from './routes/vocabulary/edit.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyIndexRoute = VocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyNewRoute = VocabularyNewRouteImport.update({
  id: '/vocabulary/new',
  path: '/vocabulary/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyIdRoute = VocabularyIdRouteImport.update({
  id: '/vocabulary/$id',
  path: '/vocabulary/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyEditIdRoute = VocabularyEditIdRouteImport.update({
  id: '/vocabulary/edit/$id',
  path: '/vocabulary/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/vocabulary/$id': typeof VocabularyIdRoute
  '/vocabulary/new': typeof VocabularyNewRoute
  '/vocabulary': typeof VocabularyIndexRoute
  '/vocabulary/edit/$id': typeof VocabularyEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/vocabulary/$id': typeof VocabularyIdRoute
  '/vocabulary/new': typeof VocabularyNewRoute
  '/vocabulary': typeof VocabularyIndexRoute
  '/vocabulary/edit/$id': typeof VocabularyEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/vocabulary/$id': typeof VocabularyIdRoute
  '/vocabulary/new': typeof VocabularyNewRoute
  '/vocabulary/': typeof VocabularyIndexRoute
  '/vocabulary/edit/$id': typeof VocabularyEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/vocabulary/$id'
    | '/vocabulary/new'
    | '/vocabulary'
    | '/vocabulary/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/vocabulary/$id'
    | '/vocabulary/new'
    | '/vocabulary'
    | '/vocabulary/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/vocabulary/$id'
    | '/vocabulary/new'
    | '/vocabulary/'
    | '/vocabulary/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  VocabularyIdRoute: typeof VocabularyIdRoute
  VocabularyNewRoute: typeof VocabularyNewRoute
  VocabularyIndexRoute: typeof VocabularyIndexRoute
  VocabularyEditIdRoute: typeof VocabularyEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/': {
      id: '/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/new': {
      id: '/vocabulary/new'
      path: '/vocabulary/new'
      fullPath: '/vocabulary/new'
      preLoaderRoute: typeof VocabularyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/$id': {
      id: '/vocabulary/$id'
      path: '/vocabulary/$id'
      fullPath: '/vocabulary/$id'
      preLoaderRoute: typeof VocabularyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/edit/$id': {
      id: '/vocabulary/edit/$id'
      path: '/vocabulary/edit/$id'
      fullPath: '/vocabulary/edit/$id'
      preLoaderRoute: typeof VocabularyEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  VocabularyIdRoute: VocabularyIdRoute,
  VocabularyNewRoute: VocabularyNewRoute,
  VocabularyIndexRoute: VocabularyIndexRoute,
  VocabularyEditIdRoute: VocabularyEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
