/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VocabularyIndexRouteImport } from './routes/vocabulary/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as VocabularyNewRouteImport } from './routes/vocabulary/new'
import { Route as VocabularyIdRouteImport } from './routes/vocabulary/$id'
import { Route as StudyNewRouteImport } from './routes/study/new'
import { Route as VocabularyEditIdRouteImport } from './routes/vocabulary/edit.$id'
import { Route as StudyIdLearnRouteImport } from './routes/study/$id/learn'
import { Route as StudyIdEditRouteImport } from './routes/study/$id/edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyIndexRoute = VocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyNewRoute = VocabularyNewRouteImport.update({
  id: '/vocabulary/new',
  path: '/vocabulary/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyIdRoute = VocabularyIdRouteImport.update({
  id: '/vocabulary/$id',
  path: '/vocabulary/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyNewRoute = StudyNewRouteImport.update({
  id: '/study/new',
  path: '/study/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyEditIdRoute = VocabularyEditIdRouteImport.update({
  id: '/vocabulary/edit/$id',
  path: '/vocabulary/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdLearnRoute = StudyIdLearnRouteImport.update({
  id: '/study/$id/learn',
  path: '/study/$id/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdEditRoute = StudyIdEditRouteImport.update({
  id: '/study/$id/edit',
  path: '/study/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/study/new': typeof StudyNewRoute
  '/vocabulary/$id': typeof VocabularyIdRoute
  '/vocabulary/new': typeof VocabularyNewRoute
  '/study': typeof StudyIndexRoute
  '/vocabulary': typeof VocabularyIndexRoute
  '/study/$id/edit': typeof StudyIdEditRoute
  '/study/$id/learn': typeof StudyIdLearnRoute
  '/vocabulary/edit/$id': typeof VocabularyEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/study/new': typeof StudyNewRoute
  '/vocabulary/$id': typeof VocabularyIdRoute
  '/vocabulary/new': typeof VocabularyNewRoute
  '/study': typeof StudyIndexRoute
  '/vocabulary': typeof VocabularyIndexRoute
  '/study/$id/edit': typeof StudyIdEditRoute
  '/study/$id/learn': typeof StudyIdLearnRoute
  '/vocabulary/edit/$id': typeof VocabularyEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/study/new': typeof StudyNewRoute
  '/vocabulary/$id': typeof VocabularyIdRoute
  '/vocabulary/new': typeof VocabularyNewRoute
  '/study/': typeof StudyIndexRoute
  '/vocabulary/': typeof VocabularyIndexRoute
  '/study/$id/edit': typeof StudyIdEditRoute
  '/study/$id/learn': typeof StudyIdLearnRoute
  '/vocabulary/edit/$id': typeof VocabularyEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/study/new'
    | '/vocabulary/$id'
    | '/vocabulary/new'
    | '/study'
    | '/vocabulary'
    | '/study/$id/edit'
    | '/study/$id/learn'
    | '/vocabulary/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/study/new'
    | '/vocabulary/$id'
    | '/vocabulary/new'
    | '/study'
    | '/vocabulary'
    | '/study/$id/edit'
    | '/study/$id/learn'
    | '/vocabulary/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/study/new'
    | '/vocabulary/$id'
    | '/vocabulary/new'
    | '/study/'
    | '/vocabulary/'
    | '/study/$id/edit'
    | '/study/$id/learn'
    | '/vocabulary/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  StudyNewRoute: typeof StudyNewRoute
  VocabularyIdRoute: typeof VocabularyIdRoute
  VocabularyNewRoute: typeof VocabularyNewRoute
  StudyIndexRoute: typeof StudyIndexRoute
  VocabularyIndexRoute: typeof VocabularyIndexRoute
  StudyIdEditRoute: typeof StudyIdEditRoute
  StudyIdLearnRoute: typeof StudyIdLearnRoute
  VocabularyEditIdRoute: typeof VocabularyEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/': {
      id: '/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/new': {
      id: '/vocabulary/new'
      path: '/vocabulary/new'
      fullPath: '/vocabulary/new'
      preLoaderRoute: typeof VocabularyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/$id': {
      id: '/vocabulary/$id'
      path: '/vocabulary/$id'
      fullPath: '/vocabulary/$id'
      preLoaderRoute: typeof VocabularyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/new': {
      id: '/study/new'
      path: '/study/new'
      fullPath: '/study/new'
      preLoaderRoute: typeof StudyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/edit/$id': {
      id: '/vocabulary/edit/$id'
      path: '/vocabulary/edit/$id'
      fullPath: '/vocabulary/edit/$id'
      preLoaderRoute: typeof VocabularyEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id/learn': {
      id: '/study/$id/learn'
      path: '/study/$id/learn'
      fullPath: '/study/$id/learn'
      preLoaderRoute: typeof StudyIdLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id/edit': {
      id: '/study/$id/edit'
      path: '/study/$id/edit'
      fullPath: '/study/$id/edit'
      preLoaderRoute: typeof StudyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  StudyNewRoute: StudyNewRoute,
  VocabularyIdRoute: VocabularyIdRoute,
  VocabularyNewRoute: VocabularyNewRoute,
  StudyIndexRoute: StudyIndexRoute,
  VocabularyIndexRoute: VocabularyIndexRoute,
  StudyIdEditRoute: StudyIdEditRoute,
  StudyIdLearnRoute: StudyIdLearnRoute,
  VocabularyEditIdRoute: VocabularyEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
